
package visual;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Menu extends javax.swing.JFrame {

    ControladoraVisual miVisual = new ControladoraVisual();
    
    
    
    public Menu() {
        initComponents();
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        this.setLocationRelativeTo(null);
        setTitle("Determinación de Perfiles de Trabajo");
        cargarEncabezados();
        obtenerValoresIniciales();
        //this.setSize(960, 640);
    }
    
    public static void main(String[] args) {
        Menu miMenu = new Menu();
        miMenu.setVisible(true);
    }
    
    public void cargarEncabezados(){
        
        DefaultTableModel modeloTabla = (DefaultTableModel) tblCaracteristicas.getModel();
        modeloTabla.addColumn("Característica");
        modeloTabla.addColumn("Altamente Recomendable");
        modeloTabla.addColumn("Recomendable con reservas");
        modeloTabla.addColumn("No recomendable");
        
        String[] caracteristicas = miVisual.obtenerNombreCaracteristicas();
        Object[] fila = new Object[4];
        
        for(int i = 0; i < caracteristicas.length; i++){
            fila[0] = caracteristicas[i];
            modeloTabla.addRow(fila);
        }
    }
    
    public void obtenerValoresIniciales(){
        DefaultTableModel modeloTabla = (DefaultTableModel) tblCaracteristicas.getModel();
        miVisual.obtenerValoresIniciales(modeloTabla);
    }
    
    public void enviarPerfilesEstablecidos(){
        if(!verificarCampos()){
            List<int[]> lista= new ArrayList();
            DefaultTableModel modeloTabla = (DefaultTableModel) tblCaracteristicas.getModel();

            int[] perfilAR = new int[19];
            int[] perfilRR = new int[19];
            int[] perfilNR = new int[19];


            for(int i = 1; i < 4; i++ ){    // columna i
                for(int j = 0; j < 19; j++){    // fila j
                    if(i == 1){ // si esta en la columna de AR
                        perfilAR[j] = Integer.parseInt((String)modeloTabla.getValueAt(j, i)); // toda esa conversion para poder almacenar, unica forma que encontre 
                            
                    }else if(i == 2){ // si esta en la columna de RR
                        perfilRR[j] = Integer.parseInt((String)modeloTabla.getValueAt(j, i));

                    }else{
                        perfilNR[j] = Integer.parseInt((String)modeloTabla.getValueAt(j, i));

                    }
                }
        }
           miVisual.enviarPerfiles(perfilAR, perfilRR, perfilNR);
        }else{
        JOptionPane.showMessageDialog(null, "Complete todos los campos de las características de selección");
        }
        }
        
        public boolean verificarCampos(){
           DefaultTableModel modeloTabla = (DefaultTableModel) tblCaracteristicas.getModel();
           boolean faltante = false;
         
            for(int i = 1; i < 4; i++){
                for(int j = 0; j < 19; j++){
                    if(modeloTabla.getValueAt(j, i) == null || modeloTabla.getValueAt(j, i).equals("")) faltante = true;
                }
            }
            return faltante;
        }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
     * The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        chkMatematica = new javax.swing.JCheckBox();
        chkQuimica = new javax.swing.JCheckBox();
        chkFisica = new javax.swing.JCheckBox();
        chkProgramacion = new javax.swing.JCheckBox();
        chkElectronica = new javax.swing.JCheckBox();
        chkSimulacion = new javax.swing.JCheckBox();
        chkHistoria = new javax.swing.JCheckBox();
        chkCienciasSociales = new javax.swing.JCheckBox();
        chkBiologia = new javax.swing.JCheckBox();
        chkLiteratura = new javax.swing.JCheckBox();
        chkMetodosNumericos = new javax.swing.JCheckBox();
        chkIngles = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        chkBuenaComunicacion = new javax.swing.JCheckBox();
        chkBuenaDiccion = new javax.swing.JCheckBox();
        chkClaridadConceptos = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        chkBuenaSintaxis = new javax.swing.JCheckBox();
        chkBuenaCaligrafia = new javax.swing.JCheckBox();
        chkProlijidad = new javax.swing.JCheckBox();
        chkPorcentajeRtas = new javax.swing.JCheckBox();
        btnEvaluarPerfil = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCaracteristicas = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Evaluación de perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Promedios superiores o iguales a 8", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        chkMatematica.setText("Matemática");
        chkMatematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMatematicaActionPerformed(evt);
            }
        });

        chkQuimica.setText("Química");

        chkFisica.setText("Física");

        chkProgramacion.setText("Programación");

        chkElectronica.setText("Electrónica");

        chkSimulacion.setText("Simulación");

        chkHistoria.setText("Historia");

        chkCienciasSociales.setText("Ciencias Sociales");

        chkBiologia.setText("Biología");
        chkBiologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBiologiaActionPerformed(evt);
            }
        });

        chkLiteratura.setText("Literatura");

        chkMetodosNumericos.setText("Métodos Numéricos");

        chkIngles.setText("Inglés");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkFisica)
                            .addComponent(chkQuimica)
                            .addComponent(chkMatematica))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkHistoria)
                            .addComponent(chkBiologia)
                            .addComponent(chkCienciasSociales))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkProgramacion)
                            .addComponent(chkElectronica)
                            .addComponent(chkSimulacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkLiteratura)
                            .addComponent(chkMetodosNumericos)
                            .addComponent(chkIngles))
                        .addGap(41, 41, 41))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMatematica)
                    .addComponent(chkHistoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkQuimica)
                    .addComponent(chkCienciasSociales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkFisica)
                    .addComponent(chkBiologia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkProgramacion)
                    .addComponent(chkLiteratura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkElectronica)
                    .addComponent(chkMetodosNumericos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSimulacion)
                    .addComponent(chkIngles))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrevista", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        chkBuenaComunicacion.setText("Buena comunicación");

        chkBuenaDiccion.setText("Buena dicción");

        chkClaridadConceptos.setText("Claridad de conceptos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkBuenaComunicacion)
                    .addComponent(chkBuenaDiccion)
                    .addComponent(chkClaridadConceptos))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkBuenaComunicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkBuenaDiccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkClaridadConceptos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Evaluación escrita", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        chkBuenaSintaxis.setText("Buena sintaxis");

        chkBuenaCaligrafia.setText("Buena caligrafía");

        chkProlijidad.setText("Prolijidad");

        chkPorcentajeRtas.setText("Alto porcentaje de respuestas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkBuenaSintaxis)
                    .addComponent(chkBuenaCaligrafia)
                    .addComponent(chkProlijidad)
                    .addComponent(chkPorcentajeRtas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkBuenaSintaxis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkBuenaCaligrafia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkProlijidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkPorcentajeRtas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEvaluarPerfil.setText("Evaluar perfil");
        btnEvaluarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEvaluarPerfil)
                        .addGap(0, 645, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEvaluarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Características de selección requeridas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jScrollPane1.setViewportView(tblCaracteristicas);

        btnLimpiar.setText("Limpiar valores");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkMatematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMatematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMatematicaActionPerformed

    private void chkBiologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBiologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBiologiaActionPerformed

    private void btnEvaluarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarPerfilActionPerformed
        miVisual.limpiarLista(); // limpia lista por si se prueba nuevo vector
        int[] valoresPerfil = new int[19];
        
        if(chkMatematica.isSelected()){ valoresPerfil[0] = 1; }else{ valoresPerfil[0] = -1; }
        if(chkQuimica.isSelected()){ valoresPerfil[1] = 1; }else{ valoresPerfil[1] = -1; }
        if(chkFisica.isSelected()){ valoresPerfil[2] = 1; }else{ valoresPerfil[2] = -1; }
        if(chkProgramacion.isSelected()){ valoresPerfil[3] = 1; }else{ valoresPerfil[3] = -1; }
        if(chkElectronica.isSelected()){ valoresPerfil[4] = 1; }else{ valoresPerfil[4] = -1; }
        if(chkSimulacion.isSelected()){ valoresPerfil[5] = 1; }else{ valoresPerfil[5] = -1; }
        if(chkHistoria.isSelected()){ valoresPerfil[6] = 1; }else{ valoresPerfil[6] = -1; }
        if(chkCienciasSociales.isSelected()){ valoresPerfil[7] = 1; }else{ valoresPerfil[7] = -1; }
        if(chkBiologia.isSelected()){ valoresPerfil[8] = 1; }else{ valoresPerfil[8] = -1; }
        if(chkLiteratura.isSelected()){ valoresPerfil[9] = 1; }else{ valoresPerfil[9] = -1; }
        if(chkMetodosNumericos.isSelected()){ valoresPerfil[10] = 1; }else{ valoresPerfil[10] = -1; }
        if(chkIngles.isSelected()){ valoresPerfil[11] = 1; }else{ valoresPerfil[11] = -1; }
        if(chkBuenaComunicacion.isSelected()){ valoresPerfil[12] = 1; }else{ valoresPerfil[12] = -1; }
        if(chkBuenaDiccion.isSelected()){ valoresPerfil[13] = 1; }else{ valoresPerfil[13] = -1; }
        if(chkClaridadConceptos.isSelected()){ valoresPerfil[14] = 1; }else{ valoresPerfil[14] = -1; }
        if(chkBuenaSintaxis.isSelected()){ valoresPerfil[15] = 1; }else{ valoresPerfil[15] = -1; }
        if(chkBuenaCaligrafia.isSelected()){ valoresPerfil[16] = 1; }else{ valoresPerfil[16] = -1; }
        if(chkProlijidad.isSelected()){ valoresPerfil[17] = 1; }else{ valoresPerfil[17] = -1; }
        if(this.chkPorcentajeRtas.isSelected()){ valoresPerfil[18] = 1; }else{ valoresPerfil[18] = -1; }
        
        
        enviarPerfilesEstablecidos(); // envia los 3 perfiles a comparar
        miVisual.obtenerPerfil(valoresPerfil); // envia el perfil a evaluar
        
    }//GEN-LAST:event_btnEvaluarPerfilActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        DefaultTableModel modeloTabla = (DefaultTableModel) tblCaracteristicas.getModel();
        
        for(int i = 1; i < 4; i++){
            for(int j = 0; j < 19; j++){
                modeloTabla.setValueAt("", j, i);
            }
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluarPerfil;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox chkBiologia;
    private javax.swing.JCheckBox chkBuenaCaligrafia;
    private javax.swing.JCheckBox chkBuenaComunicacion;
    private javax.swing.JCheckBox chkBuenaDiccion;
    private javax.swing.JCheckBox chkBuenaSintaxis;
    private javax.swing.JCheckBox chkCienciasSociales;
    private javax.swing.JCheckBox chkClaridadConceptos;
    private javax.swing.JCheckBox chkElectronica;
    private javax.swing.JCheckBox chkFisica;
    private javax.swing.JCheckBox chkHistoria;
    private javax.swing.JCheckBox chkIngles;
    private javax.swing.JCheckBox chkLiteratura;
    private javax.swing.JCheckBox chkMatematica;
    private javax.swing.JCheckBox chkMetodosNumericos;
    private javax.swing.JCheckBox chkPorcentajeRtas;
    private javax.swing.JCheckBox chkProgramacion;
    private javax.swing.JCheckBox chkProlijidad;
    private javax.swing.JCheckBox chkQuimica;
    private javax.swing.JCheckBox chkSimulacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCaracteristicas;
    // End of variables declaration//GEN-END:variables
}
